

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR  = "USER_LOGIN_ERROR";
export const USER_CLEAR_STATE = "USER_CLEAR_STATE";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_ERROR = "USER_LIST_ERROR";
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"